/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideIcon: typeof import('./src/components/SideIcon.vue')['default']
    UiButton: typeof import('./src/components/ui/UiButton.vue')['default']
    UiCheckButton: typeof import('./src/components/ui/UiCheckButton.vue')['default']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
  }
}
